### ISSUE TITLE
GtkTextView doesn't support property bottom_margin

### ISSUE THREAD

**Issue by PaulTimmins** [tanwald/passpy#1]
removing top_margin and bottom_margin properties from the mainview.py, around line 132 fixes the issue and the program launches

Traceback (most recent call last):
  File "/home/paul/dev/passpy/pass.py", line 81, in do_activate
    self.window = Window(self)
  File "/home/paul/dev/passpy/gui/window.py", line 31, in **init**
    self.mainView = MainView(app, self)
  File "/home/paul/dev/passpy/gui/mainview.py", line 30, in **init**
    self.setItemData()
  File "/home/paul/dev/passpy/gui/mainview.py", line 132, in setItemData
    left_margin=25
TypeError: gobject `GtkTextView' doesn't support property`bottom_margin'

**Comment by tanwald** [comment]
thank you. most probably you are using an older version of pygobject. you need pygobject3. here you find the package names for fedora, debian, ubuntu: [https://wiki.gnome.org/Projects/PyGObject](https://wiki.gnome.org/Projects/PyGObject) (can be installed via dnf, apt-get...)would be great if you could post the packages needed. then i could update the requirements.you should get a warning in terminal...
